### ISSUE TITLE
CORS error 

### ISSUE THREAD

**Issue by bendavis78** [InstaGIS/googlemaps-loader#1]
Getting CORS error when using jspm / systemjs. Any ideas?

XMLHttpRequest cannot load https://maps.googleapis.com/maps/api/js. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:8080' is therefore not allowed access.

**Comment by ffflabs** [comment]
Are you sure you are declaring the meta for the full google api url?

Please see

https://github.com/HuasoFoundries/googlemaps-loader/commit/cc62f871eba25e459f6aa5a4d7b04a67b85c6471#commitcomment-17171029

**Comment by ffflabs** [comment]
To clarify: at some point in March the SystemJS release _"changed something"_ which I didnt investigate enough, but the relevant part is that using

``` js
System.config({
  paths: {
      "github:*": "jspm_packages/github/*",
      "npm:*": "jspm_packages/npm/*",
      "gmaps": "https://maps.googleapis.com/maps/api/js"
    },

  meta: {
    "gmaps": {
      "build": false,
        "parameters": {
          "v": "3.exp",
          "key":"API key"
        },
        "loader": "gmap"
    }
  }
});
```

wasn't working anymore, as it tried to load `https://maps.googleapis.com/maps/api/js` directly, without the loader. The `meta` config was ignored. And the change needed to fix it was to declare the meta for the full url:

``` js
meta: {
    "https://maps.googleapis.com/maps/api/*": {
      "build": false,
      "parameters": {
        "v": "3.exp",
        "key":"API key"
      },
      "loader": "gmap"
    }

  }
```

I'm closing this issue due to no further actions. I guess the only reccomendation I can give you guys is to make sure you are using the config that's shown in the README of this repo.
